services:
  # 1. DATABASE
  bengkel_db:
    image: mysql:5.7
    container_name: bengkel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bengkel_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Load script SQL otomatis
    networks:
      - app_network

  # 2. BACKEND
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - "5000:80"
    depends_on:
      - bengkel_db
    networks:
      - app_network

  # 3. FRONTEND
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge