version: '3.8'

services:
  # 1. FRONTEND (React) - Port 8080
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  # 2. BACKEND (PHP) - Port 5000
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - "5000:80"
    # extra_hosts: Ini trik agar Docker Linux bisa panggil host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network
    volumes:
      - ./backend/src:/var/www/html

# Network biar Frontend & Backend bisa ngobrol
networks:
  app_network:
    driver: bridge