version: '3.8'

services:
  # 1. DATABASE SERVICE
  bengkel_db:
    image: mysql:5.7
    container_name: bengkel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bengkel_db
    ports:
      - "3307:3306" # Akses dari luar pakai port 3307 biar gak bentrok XAMPP
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # 2. BACKEND SERVICE (PHP)
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - "5000:80"  # Mapping Port: Komputer 5000 -> Container PHP 80
    depends_on:
      - bengkel_db
    networks:
      - app_network

  # 3. FRONTEND SERVICE (React)
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge